version: 0.0
os: linux

files:
  - source: synergy-backend
    destination: /home/ubuntu/app

hooks:
  BeforeInstall:
    - location: scripts/deploy.sh
      timeout: 300
      runas: ubuntu

  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 600
      runas: ubuntu

  ApplicationStart:
    - location: scripts/deploy.sh
      timeout: 300
      runas: ubuntu
